<a href="https://colab.research.google.com/github/gbiamgaurav/NLP/blob/main/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## How to do integer encoding using keras

In [53]:
docs = ["recurrent neural network",
        "neural network",
        "artificial neural",
        "connection between nodes",
        "can create a cycle",
        "allowing output",
        "some nodes to affect subsequent",
        "exhibit temporal",
        "dynamic behviour",
        "type of Neural Network",
        "affect subsequent"]

In [54]:
type(docs)

list

In [55]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token="<nothing>")

In [56]:
tokenizer.fit_on_texts(docs)

In [57]:
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connection': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behviour': 22,
 'type': 23,
 'of': 24}

In [58]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 4),
             ('network', 3),
             ('artificial', 1),
             ('connection', 1),
             ('between', 1),
             ('nodes', 2),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('some', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('behviour', 1),
             ('type', 1),
             ('of', 1)])

In [59]:
tokenizer.document_count

11

In [60]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [61]:
from keras.utils import pad_sequences

In [62]:
sequences = pad_sequences(sequences, padding="post")

sequences

array([[ 7,  2,  3,  0,  0],
       [ 2,  3,  0,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  2,  3,  0],
       [ 5,  6,  0,  0,  0]], dtype=int32)

## Sentiment Analysis on IMDB dataset

In [63]:
data_path = "https://raw.githubusercontent.com/Ankit152/IMDB-sentiment-analysis/master/IMDB-Dataset.csv"

In [64]:
import pandas as pd
import numpy as np

In [65]:
df = pd.read_csv(data_path)

df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [66]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Flatten

In [67]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [68]:
print("Shape of Training data: ", X_train.shape)

print("Shape of Testing data: ", X_test.shape)

Shape of Training data:  (25000,)
Shape of Testing data:  (25000,)


In [69]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [70]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [71]:
print(len(X_train[0]))
print(len(X_train[1]))

218
189


In [72]:
X_train = pad_sequences(X_train, padding="post", maxlen=50)
X_test = pad_sequences(X_test, padding="post", maxlen=50)

In [73]:
X_train.shape

(25000, 50)

In [74]:
X_test.shape

(25000, 50)

In [75]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [76]:
print(len(X_train[0]))
print(len(X_train[1]))

50
50


In [77]:
model = Sequential()

model.add(SimpleRNN(32, input_shape = (50, 1), return_sequences = False))
model.add(Dense(1, activation="sigmoid"))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1,121
Trainable params: 1,121
Non-trainable params: 0
_________________________________________________________________


In [78]:
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

model.fit(X_train, y_train, epochs=3, validation_data=(X_test, y_test))

Epoch 1/3
782/782 [==============================] - 33s 40ms/step - loss: 0.6952 - accuracy: 0.5082 - val_loss: 0.6935 - val_accuracy: 0.5013
Epoch 2/3
782/782 [==============================] - 31s 40ms/step - loss: 0.6930 - accuracy: 0.5097 - val_loss: 0.6944 - val_accuracy: 0.5021
Epoch 3/3
782/782 [==============================] - 37s 47ms/step - loss: 0.6931 - accuracy: 0.5066 - val_loss: 0.6954 - val_accuracy: 0.5006


In [79]:
X_test[0].shape

(50,)

In [80]:
X_test[0].reshape(1, -1)

array([[  394,   354,     4,   123,     9,  1035,  1035,  1035,    10,
           10,    13,    92,   124,    89,   488,  7944,   100,    28,
         1668,    14,    31,    23,    27,  7479,    29,   220,   468,
            8,   124,    14,   286,   170,     8,   157,    46,     5,
           27,   239,    16,   179, 15387,    38,    32,    25,  7944,
          451,   202,    14,     6,   717]], dtype=int32)

In [81]:
X_test[0].reshape(1, -1).shape

(1, 50)

In [82]:
pred_test = X_test[0].reshape(1, -1)

In [83]:
prediction = model.predict(pred_test)[0]

prediction

1/1 [==============================] - 0s 128ms/step


array([0.52886134], dtype=float32)

In [84]:
if prediction > 0.5:
  print("Positive Sentiment")
else:
  print("Negative Sentiment")

Positive Sentiment


## How to do encoding using keras embedding layers

In [85]:
docs

['recurrent neural network',
 'neural network',
 'artificial neural',
 'connection between nodes',
 'can create a cycle',
 'allowing output',
 'some nodes to affect subsequent',
 'exhibit temporal',
 'dynamic behviour',
 'type of Neural Network',
 'affect subsequent']

In [86]:
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

In [87]:
tokenizer.fit_on_texts(docs)

In [88]:
len(tokenizer.word_index)

23

In [89]:
sequences = tokenizer.texts_to_sequences(docs)

sequences

[[6, 1, 2],
 [1, 2],
 [7, 1],
 [8, 9, 3],
 [10, 11, 12, 13],
 [14, 15],
 [16, 3, 17, 4, 5],
 [18, 19],
 [20, 21],
 [22, 23, 1, 2],
 [4, 5]]

In [90]:
## Applying Padding

from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding="post")
sequences

array([[ 6,  1,  2,  0,  0],
       [ 1,  2,  0,  0,  0],
       [ 7,  1,  0,  0,  0],
       [ 8,  9,  3,  0,  0],
       [10, 11, 12, 13,  0],
       [14, 15,  0,  0,  0],
       [16,  3, 17,  4,  5],
       [18, 19,  0,  0,  0],
       [20, 21,  0,  0,  0],
       [22, 23,  1,  2,  0],
       [ 4,  5,  0,  0,  0]], dtype=int32)

In [91]:
## Define embedding architecture, 23 is the unique words, dim is dimension, input_lenth is the max length

from keras import Sequential
from keras.layers import Dense, SimpleRNN, Flatten, Embedding

model = Sequential()
model.add(Embedding(23, output_dim=2, input_length=5))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 5, 2)              46        
                                                                 
Total params: 46
Trainable params: 46
Non-trainable params: 0
_________________________________________________________________


In [92]:
model.compile("adam", "accuracy")

In [93]:
docs

['recurrent neural network',
 'neural network',
 'artificial neural',
 'connection between nodes',
 'can create a cycle',
 'allowing output',
 'some nodes to affect subsequent',
 'exhibit temporal',
 'dynamic behviour',
 'type of Neural Network',
 'affect subsequent']

In [94]:
pred = model.predict(sequences)

pred

1/1 [==============================] - 0s 40ms/step


array([[[-0.00343517,  0.02468986],
        [-0.00428339,  0.00018084],
        [-0.02781541,  0.00421469],
        [ 0.01075485, -0.03873447],
        [ 0.01075485, -0.03873447]],

       [[-0.00428339,  0.00018084],
        [-0.02781541,  0.00421469],
        [ 0.01075485, -0.03873447],
        [ 0.01075485, -0.03873447],
        [ 0.01075485, -0.03873447]],

       [[-0.03060827, -0.03813988],
        [-0.00428339,  0.00018084],
        [ 0.01075485, -0.03873447],
        [ 0.01075485, -0.03873447],
        [ 0.01075485, -0.03873447]],

       [[ 0.03531626, -0.04722689],
        [-0.00856429,  0.01810545],
        [ 0.04047873,  0.03943238],
        [ 0.01075485, -0.03873447],
        [ 0.01075485, -0.03873447]],

       [[-0.00234039, -0.04205092],
        [-0.00691529, -0.02579706],
        [ 0.00180124, -0.02088481],
        [-0.00929457,  0.02754493],
        [ 0.01075485, -0.03873447]],

       [[-0.03307084,  0.03698805],
        [-0.02396079, -0.04425105],
        [ 0.010754

### Sentiment Analysis using Embedding layers

In [95]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [96]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [97]:
X_train = pad_sequences(X_train, padding="post", maxlen=50)
X_test = pad_sequences(X_test, padding="post", maxlen=50)

In [98]:
X_train.shape
X_test.shape

(25000, 50)

In [99]:
## Define the architecture

model = Sequential()
model.add(Embedding(10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation="sigmoid"))

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [100]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["acc"])
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 [==============================] - 73s 91ms/step - loss: 0.6907 - acc: 0.5267 - val_loss: 0.6796 - val_acc: 0.5733
Epoch 2/5
782/782 [==============================] - 53s 67ms/step - loss: 0.5181 - acc: 0.7410 - val_loss: 0.4403 - val_acc: 0.7985
Epoch 3/5
782/782 [==============================] - 46s 59ms/step - loss: 0.3526 - acc: 0.8494 - val_loss: 0.4242 - val_acc: 0.8088
Epoch 4/5
782/782 [==============================] - 49s 62ms/step - loss: 0.2854 - acc: 0.8861 - val_loss: 0.4829 - val_acc: 0.8034
Epoch 5/5
782/782 [==============================] - 46s 59ms/step - loss: 0.2429 - acc: 0.9043 - val_loss: 0.4923 - val_acc: 0.7959


In [101]:
pred_test = X_test[0][0:50].reshape(1, -1)

pred_test

array([[  394,   354,     4,   123,     9,  1035,  1035,  1035,    10,
           10,    13,    92,   124,    89,   488,  7944,   100,    28,
         1668,    14,    31,    23,    27,  7479,    29,   220,   468,
            8,   124,    14,   286,   170,     8,   157,    46,     5,
           27,   239,    16,   179, 15387,    38,    32,    25,  7944,
          451,   202,    14,     6,   717]], dtype=int32)

In [103]:
prediction = model.predict(pred_test)

prediction

1/1 [==============================] - 0s 32ms/step


array([[0.03529444]], dtype=float32)

In [104]:
if prediction > 0.5:
  print("Positive Sentiment")
else:
  print("Negative Sentiment")

Negative Sentiment
