<a href="https://colab.research.google.com/github/gbiamgaurav/NLP/blob/main/Word_Embedding_%26_LSTM_practical_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Word Embedding Techniques using Embedding Layer in Keras

In [4]:
### Libraries USed Tensorflow> 2.0  and keras

!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [6]:
##tensorflow >2.0

from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [15]:
## Vocabulary size

voc_size = 10000

## One - Hot Representation

In [16]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[9970, 8226, 4275, 3046], [9970, 8226, 4275, 2320], [9970, 1651, 4275, 5986], [9330, 1868, 6320, 8179, 6043], [9330, 1868, 6320, 8179, 5214], [7088, 9970, 6459, 4275, 2118], [1563, 5401, 4391, 8179]]


## Word Embedding Representation

In [17]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences # pre padding & post padding
from tensorflow.keras.models import Sequential

In [18]:
import numpy as np

## Pre Padding

In [19]:
sent_length = 8

embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

In [20]:
print(embedded_docs)

[[   0    0    0    0 9970 8226 4275 3046]
 [   0    0    0    0 9970 8226 4275 2320]
 [   0    0    0    0 9970 1651 4275 5986]
 [   0    0    0 9330 1868 6320 8179 6043]
 [   0    0    0 9330 1868 6320 8179 5214]
 [   0    0    0 7088 9970 6459 4275 2118]
 [   0    0    0    0 1563 5401 4391 8179]]


## Post Padding

In [22]:
embedded_docs = pad_sequences(onehot_repr, padding='post', maxlen=sent_length)

print(embedded_docs)

[[9970 8226 4275 3046    0    0    0    0]
 [9970 8226 4275 2320    0    0    0    0]
 [9970 1651 4275 5986    0    0    0    0]
 [9330 1868 6320 8179 6043    0    0    0]
 [9330 1868 6320 8179 5214    0    0    0]
 [7088 9970 6459 4275 2118    0    0    0]
 [1563 5401 4391 8179    0    0    0    0]]


In [23]:
## 10 feature dimensions

dim = 10

## Create a Model

In [24]:
model = Sequential()

model.add(Embedding(voc_size, 10, input_length=sent_length))

model.compile('adam', 'mse')

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [28]:
'the glass of milk'
embedded_docs[0]

array([9970, 8226, 4275, 3046,    0,    0,    0,    0], dtype=int32)

In [29]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[-0.01750458, -0.03404515, -0.01858233,  0.03257856,  0.04929498,
        -0.00177536,  0.01616636,  0.012118  , -0.00747627, -0.04241472],
       [-0.04834662,  0.0268978 , -0.01682065,  0.01677194, -0.04448731,
         0.00612178, -0.04487002,  0.03579732,  0.03713492,  0.03369912],
       [-0.03710579, -0.04361148,  0.03227798,  0.00135171, -0.02748399,
         0.03492543, -0.0341462 , -0.01541172, -0.01409209, -0.00748793],
       [ 0.00467826,  0.00442022,  0.01460977, -0.01025655,  0.00103816,
        -0.00077721, -0.00279514,  0.03537117,  0.01402387,  0.00884743],
       [ 0.03182806, -0.02075398, -0.04745043, -0.01801939,  0.0301291 ,
        -0.00981586, -0.00032576, -0.03836839, -0.01134453,  0.02724269],
       [ 0.03182806, -0.02075398, -0.04745043, -0.01801939,  0.0301291 ,
        -0.00981586, -0.00032576, -0.03836839, -0.01134453,  0.02724269],
       [ 0.03182806, -0.02075398, -0.04745043, -0.01801939,  0.0301291 ,
        -0.00981586, -0.00032576, -0.03836839

In [32]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 19ms/step
[[[-0.01750458 -0.03404515 -0.01858233  0.03257856  0.04929498
   -0.00177536  0.01616636  0.012118   -0.00747627 -0.04241472]
  [-0.04834662  0.0268978  -0.01682065  0.01677194 -0.04448731
    0.00612178 -0.04487002  0.03579732  0.03713492  0.03369912]
  [-0.03710579 -0.04361148  0.03227798  0.00135171 -0.02748399
    0.03492543 -0.0341462  -0.01541172 -0.01409209 -0.00748793]
  [ 0.00467826  0.00442022  0.01460977 -0.01025655  0.00103816
   -0.00077721 -0.00279514  0.03537117  0.01402387  0.00884743]
  [ 0.03182806 -0.02075398 -0.04745043 -0.01801939  0.0301291
   -0.00981586 -0.00032576 -0.03836839 -0.01134453  0.02724269]
  [ 0.03182806 -0.02075398 -0.04745043 -0.01801939  0.0301291
   -0.00981586 -0.00032576 -0.03836839 -0.01134453  0.02724269]
  [ 0.03182806 -0.02075398 -0.04745043 -0.01801939  0.0301291
   -0.00981586 -0.00032576 -0.03836839 -0.01134453  0.02724269]
  [ 0.03182806 -0.02075398 -0.04745043 -0.01801939  0.0301291


## Assignment 

In [34]:
### Assignment

sentences =["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [35]:
sentences

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [37]:
## Vocabulary size 

voc_size = 500

In [38]:
## One-hot representation

onehot_repr=[one_hot(words,voc_size)for words in sentences] 
print(onehot_repr)

[[24, 1, 29, 345, 305, 330], [60, 143, 29, 250, 449, 216], [53, 26, 102, 173], [24, 381, 29, 458, 24, 417], [33, 203, 290, 29, 250, 449, 216], [362, 29, 250, 449, 106, 436]]


## Word Embedding 

## Pre Padding

In [39]:
len(sentences)

6

In [40]:
sent_length = 10

In [41]:
embedded_layer = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

print(embedded_layer)

[[  0   0   0   0  24   1  29 345 305 330]
 [  0   0   0   0  60 143  29 250 449 216]
 [  0   0   0   0   0   0  53  26 102 173]
 [  0   0   0   0  24 381  29 458  24 417]
 [  0   0   0  33 203 290  29 250 449 216]
 [  0   0   0   0 362  29 250 449 106 436]]


In [42]:
dim = 10

In [47]:
## Create the model

model_1 = Sequential()

model_1.add(Embedding(voc_size, 10, input_length=sent_length))

model_1.compile('adam', 'mse')

In [48]:
model_1.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 10, 10)            5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [49]:
print((model_1.predict(embedded_layer)))

1/1 [==============================] - 0s 36ms/step
[[[-0.01087321 -0.01471263 -0.04918385  0.01761551 -0.02410309
   -0.00622088  0.0090157   0.02566952  0.01207119  0.01509565]
  [-0.01087321 -0.01471263 -0.04918385  0.01761551 -0.02410309
   -0.00622088  0.0090157   0.02566952  0.01207119  0.01509565]
  [-0.01087321 -0.01471263 -0.04918385  0.01761551 -0.02410309
   -0.00622088  0.0090157   0.02566952  0.01207119  0.01509565]
  [-0.01087321 -0.01471263 -0.04918385  0.01761551 -0.02410309
   -0.00622088  0.0090157   0.02566952  0.01207119  0.01509565]
  [-0.03870965 -0.02665251 -0.01604303  0.03413187  0.02118761
   -0.03043215  0.03084027  0.03437665  0.04144642 -0.03121346]
  [ 0.03997518 -0.02842474 -0.03404038 -0.03429512  0.0445424
    0.02414997 -0.03045487  0.02242026  0.03402854 -0.03524588]
  [ 0.03176376  0.01309195  0.01526947  0.02500725  0.01826406
   -0.04296391  0.03498873 -0.01757892  0.03398154  0.00093329]
  [ 0.02824536 -0.03531535 -0.00998791  0.04104115  0.040720