<a href="https://colab.research.google.com/github/gbiamgaurav/NLP/blob/main/word_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({"text": ["people watch data science videos",
                   "people write comments",
                            "data science watches videos"], "output": [1,1,0]})

In [4]:
df

text  output
0  people watch data science videos       1
1             people write comments       1
2       data science watches videos       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df["text"])

In [7]:
## vocabulary

print(cv.vocabulary_)

{'people': 2, 'watch': 5, 'data': 1, 'science': 3, 'videos': 4, 'write': 7, 'comments': 0, 'watches': 6}


In [9]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 1 1 0 0]]
[[1 0 1 0 0 0 0 1]]
[[0 1 0 1 1 0 1 0]]


### N-Grams

In [10]:
## BI gram

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(2,2))

In [11]:
bow = cv.fit_transform(df["text"])

In [12]:
print(cv.vocabulary_)

{'people watch': 1, 'watch data': 5, 'data science': 0, 'science videos': 3, 'people write': 2, 'write comments': 7, 'science watches': 4, 'watches videos': 6}


### TFIDF

In [13]:
## TFIDF

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

In [15]:
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.41779577, 0.41779577, 0.41779577, 0.41779577,
        0.54935123, 0.        , 0.        ],
       [0.62276601, 0.        , 0.4736296 , 0.        , 0.        ,
        0.        , 0.        , 0.62276601],
       [0.        , 0.45985353, 0.        , 0.45985353, 0.45985353,
        0.        , 0.60465213, 0.        ]])

In [17]:
print(tfidf.get_feature_names_out())

['comments' 'data' 'people' 'science' 'videos' 'watch' 'watches' 'write']


### Word2Vec